config/routes.rb
Tda::Application.routes.draw do
  get "trade/list"

  resources :trades

end

app/models/trade.rb
require 'open-uri'

class Trade < ActiveRecord::Base

  attr_accessible :order_date_time, :executed_date, :trade_type, :sub_type, :buy_sell_code, :asset_type, :symbol, :description, :cusip,
      :price, :quantity, :transaction_id, :value, :commission, :order_number, :fees, :additional_fees, :cash_balance_effect, :open_close,
      :option_expire_date, :option_underlying_symbol, :option_type, :option_strike, :accrued_interest, :shares_before, :shares_after, :other_charges,
      :redemption_fee, :cdsc_fee, :bond_interest_rate, :account_type

  validates  :order_number, :transaction_id, :uniqueness => true

  def self.get
    #TODO - service, cursor
    doc = Nokogiri::XML(open('http://localhost:8881/history.xml'))
    doc.xpath('//transaction-list').each do |transaction|
      t = Trade.new
      transaction.children.each do |child|
        name = child.name.underscore.to_sym
        if name == :type
          name = :trade_type
        end
        t[name] = child.content
      end
      t.save
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @trades }
    end
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
    @trade = Trade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @trade }
    end
  end

  # GET /trades/new
  # GET /trades/new.json
  def new
    @trade = Trade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @trade }
    end
  end

  # GET /trades/1/edit
  def edit
    @trade = Trade.find(params[:id])
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(params[:trade])

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, :notice => 'Trade was successfully created.' }
        format.json { render :json => @trade, :status => :created, :location => @trade }
      else
        format.html { render :action => "new" }
        format.json { render :json => @trade.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trades/1
  # PUT /trades/1.json
  def update
    @trade = Trade.find(params[:id])

    respond_to do |format|
      if @trade.update_attributes(params[:trade])
        format.html { redirect_to @trade, :notice => 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @trade.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/trades/_form.html.erb
<%= form_for @trade do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :order_date_time %><br />
    <%= f.datetime_select :order_date_time %>
  </p>
  <p>
    <%= f.label :executed_date %><br />
    <%= f.datetime_select :executed_date %>
  </p>
  <p>
    <%= f.label :trade_type %><br />
    <%= f.text_field :trade_type %>
  </p>
  <p>
    <%= f.label :sub_type %><br />
    <%= f.text_field :sub_type %>
  </p>
  <p>
    <%= f.label :buy_sell_code %><br />
    <%= f.text_field :buy_sell_code %>
  </p>
  <p>
    <%= f.label :asset_type %><br />
    <%= f.text_field :asset_type %>
  </p>
  <p>
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :cusip %><br />
    <%= f.number_field :cusip %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </p>
  <p>
    <%= f.label :transaction_id %><br />
    <%= f.text_field :transaction_id %>
  </p>
  <p>
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.label :commission %><br />
    <%= f.text_field :commission %>
  </p>
  <p>
    <%= f.label :order_number %><br />
    <%= f.text_field :order_number %>
  </p>
  <p>
    <%= f.label :fees %><br />
    <%= f.text_field :fees %>
  </p>
  <p>
    <%= f.label :additional_fees %><br />
    <%= f.text_field :additional_fees %>
  </p>
  <p>
    <%= f.label :cash_balance_effect %><br />
    <%= f.check_box :cash_balance_effect %>
  </p>
  <p>
    <%= f.label :open_close %><br />
    <%= f.text_field :open_close %>
  </p>
  <p>
    <%= f.label :option_expire_date %><br />
    <%= f.datetime_select :option_expire_date %>
  </p>
  <p>
    <%= f.label :option_underlying_symbol %><br />
    <%= f.text_field :option_underlying_symbol %>
  </p>
  <p>
    <%= f.label :option_type %><br />
    <%= f.text_field :option_type %>
  </p>
  <p>
    <%= f.label :option_strike %><br />
    <%= f.text_field :option_strike %>
  </p>
  <p>
    <%= f.label :accrued_interest %><br />
    <%= f.text_field :accrued_interest %>
  </p>
  <p>
    <%= f.label :shares_before %><br />
    <%= f.number_field :shares_before %>
  </p>
  <p>
    <%= f.label :shares_after %><br />
    <%= f.number_field :shares_after %>
  </p>
  <p>
    <%= f.label :other_charges %><br />
    <%= f.text_field :other_charges %>
  </p>
  <p>
    <%= f.label :redemption_fee %><br />
    <%= f.text_field :redemption_fee %>
  </p>
  <p>
    <%= f.label :cdsc_fee %><br />
    <%= f.text_field :cdsc_fee %>
  </p>
  <p>
    <%= f.label :bond_interest_rate %><br />
    <%= f.text_field :bond_interest_rate %>
  </p>
  <p>
    <%= f.label :account_type %><br />
    <%= f.number_field :account_type %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/trades/edit.html.erb
<% title "Edit Trade" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @trade %> |
  <%= link_to "View All", trades_path %>
</p>

app/views/trades/index.html.erb
<% title "Trades" %>

<table>
  <tr>
    <th>Order Date Time</th>
    <th>Executed Date</th>
    <th>Trade Type</th>
    <th>Sub Type</th>
    <th>Buy Sell Code</th>
    <th>Asset Type</th>
    <th>Symbol</th>
    <th>Description</th>
    <th>Cusip</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Transaction</th>
    <th>Value</th>
    <th>Commission</th>
    <th>Order Number</th>
    <th>Fees</th>
    <th>Additional Fees</th>
    <th>Cash Balance Effect</th>
    <th>Open Close</th>
    <th>Option Expire Date</th>
    <th>Option Underlying Symbol</th>
    <th>Option Type</th>
    <th>Option Strike</th>
    <th>Accrued Interest</th>
    <th>Shares Before</th>
    <th>Shares After</th>
    <th>Other Charges</th>
    <th>Redemption Fee</th>
    <th>Cdsc Fee</th>
    <th>Bond Interest Rate</th>
    <th>Account Type</th>
  </tr>
  <% for trade in @trades %>
    <tr>
      <td><%= trade.order_date_time %></td>
      <td><%= trade.executed_date %></td>
      <td><%= trade.trade_type %></td>
      <td><%= trade.sub_type %></td>
      <td><%= trade.buy_sell_code %></td>
      <td><%= trade.asset_type %></td>
      <td><%= trade.symbol %></td>
      <td><%= trade.description %></td>
      <td><%= trade.cusip %></td>
      <td><%= trade.price %></td>
      <td><%= trade.quantity %></td>
      <td><%= trade.transaction_id %></td>
      <td><%= trade.value %></td>
      <td><%= trade.commission %></td>
      <td><%= trade.order_number %></td>
      <td><%= trade.fees %></td>
      <td><%= trade.additional_fees %></td>
      <td><%= trade.cash_balance_effect %></td>
      <td><%= trade.open_close %></td>
      <td><%= trade.option_expire_date %></td>
      <td><%= trade.option_underlying_symbol %></td>
      <td><%= trade.option_type %></td>
      <td><%= trade.option_strike %></td>
      <td><%= trade.accrued_interest %></td>
      <td><%= trade.shares_before %></td>
      <td><%= trade.shares_after %></td>
      <td><%= trade.other_charges %></td>
      <td><%= trade.redemption_fee %></td>
      <td><%= trade.cdsc_fee %></td>
      <td><%= trade.bond_interest_rate %></td>
      <td><%= trade.account_type %></td>
      <td><%= link_to "Show", trade %></td>
      <td><%= link_to "Edit", edit_trade_path(trade) %></td>
      <td><%= link_to "Destroy", trade, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Trade", new_trade_path %></p>

app/views/trades/new.html.erb
<% title "New Trade" %>

<%= render 'form' %>

<p><%= link_to "Back to List", trades_path %></p>

app/views/trades/show.html.erb
<% title "Trade" %>

<p>
  <strong>Order Date Time:</strong>
  <%= @trade.order_date_time %>
</p>
<p>
  <strong>Executed Date:</strong>
  <%= @trade.executed_date %>
</p>
<p>
  <strong>Trade Type:</strong>
  <%= @trade.trade_type %>
</p>
<p>
  <strong>Sub Type:</strong>
  <%= @trade.sub_type %>
</p>
<p>
  <strong>Buy Sell Code:</strong>
  <%= @trade.buy_sell_code %>
</p>
<p>
  <strong>Asset Type:</strong>
  <%= @trade.asset_type %>
</p>
<p>
  <strong>Symbol:</strong>
  <%= @trade.symbol %>
</p>
<p>
  <strong>Description:</strong>
  <%= @trade.description %>
</p>
<p>
  <strong>Cusip:</strong>
  <%= @trade.cusip %>
</p>
<p>
  <strong>Price:</strong>
  <%= @trade.price %>
</p>
<p>
  <strong>Quantity:</strong>
  <%= @trade.quantity %>
</p>
<p>
  <strong>Transaction:</strong>
  <%= @trade.transaction_id %>
</p>
<p>
  <strong>Value:</strong>
  <%= @trade.value %>
</p>
<p>
  <strong>Commission:</strong>
  <%= @trade.commission %>
</p>
<p>
  <strong>Order Number:</strong>
  <%= @trade.order_number %>
</p>
<p>
  <strong>Fees:</strong>
  <%= @trade.fees %>
</p>
<p>
  <strong>Additional Fees:</strong>
  <%= @trade.additional_fees %>
</p>
<p>
  <strong>Cash Balance Effect:</strong>
  <%= @trade.cash_balance_effect %>
</p>
<p>
  <strong>Open Close:</strong>
  <%= @trade.open_close %>
</p>
<p>
  <strong>Option Expire Date:</strong>
  <%= @trade.option_expire_date %>
</p>
<p>
  <strong>Option Underlying Symbol:</strong>
  <%= @trade.option_underlying_symbol %>
</p>
<p>
  <strong>Option Type:</strong>
  <%= @trade.option_type %>
</p>
<p>
  <strong>Option Strike:</strong>
  <%= @trade.option_strike %>
</p>
<p>
  <strong>Accrued Interest:</strong>
  <%= @trade.accrued_interest %>
</p>
<p>
  <strong>Shares Before:</strong>
  <%= @trade.shares_before %>
</p>
<p>
  <strong>Shares After:</strong>
  <%= @trade.shares_after %>
</p>
<p>
  <strong>Other Charges:</strong>
  <%= @trade.other_charges %>
</p>
<p>
  <strong>Redemption Fee:</strong>
  <%= @trade.redemption_fee %>
</p>
<p>
  <strong>Cdsc Fee:</strong>
  <%= @trade.cdsc_fee %>
</p>
<p>
  <strong>Bond Interest Rate:</strong>
  <%= @trade.bond_interest_rate %>
</p>
<p>
  <strong>Account Type:</strong>
  <%= @trade.account_type %>
</p>

<p>
  <%= link_to "Edit", edit_trade_path(@trade) %> |
  <%= link_to "Destroy", @trade, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", trades_path %>
</p>